version: '3.8'

services:
  backend:
    build: ./backend
    container_name: writeNow-backend
    ports:
      - '8000:8000'
    env_file:
      - ./backend/.env
    networks:
      - writeNow-network
    # Allow external connections
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  frontend:
    build: ./frontend
    container_name: writeNow-frontend
    ports:
      - '80:80'
    depends_on:
      - backend
    networks:
      - writeNow-network

networks:
  writeNow-network:
    driver: bridge
